### ISSUE TITLE
java.lang.NoSuchMethodError: No static method onStartNestedScroll error on Android

### ISSUE THREAD

**Issue by broding** [zendesk/sdk_unity_plugin#93]
The following error is causing my game to crash when accessing a FAQ question in the FAQ menu. We're running Unity 2018.3.14 and build using Gradle. Does anyone have any quick pointers?

`2019-11-20 09:10:22.314 30388-30388/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.littlechicken.fireflush, PID: 30388
    java.lang.NoSuchMethodError: No static method onStartNestedScroll(Landroid/view/ViewParent;Landroid/view/View;Landroid/view/View;II)Z in class Landroid/support/v4/view/ViewParentCompat; or its super classes (declaration of 'android.support.v4.view.ViewParentCompat' appears in base.apk!classes91.dex)
        at android.support.v4.view.NestedScrollingChildHelper.startNestedScroll(NestedScrollingChildHelper.java:152)
        at android.support.v4.view.NestedScrollingChildHelper.startNestedScroll(NestedScrollingChildHelper.java:128)
        at android.support.v7.widget.RecyclerView.startNestedScroll(RecyclerView.java:10446)
        at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2662)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
        at com.facebook.ads.redexgen.X.9F.dispatchTouchEvent(:19570)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
2019-11-20 09:10:22.314 30388-30388/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
